### ISSUE TITLE
Dear platformer.

### ISSUE THREAD

**Issue by tgcofficial** [platformerdotio/platformerdotio.github.io#4]
Hello, you must know me as TGC OFFICIAL, but I have one concern. You never asked me for you take my CSS and games and name it yours, if you keep this up I will contact higher ups. We can talk this out over via Discord "saturn#0020" 

- saturn

**Comment by krazykoolkat** [comment]
Hello, My friend Smartfolio contacted you and he said you agreed to help with our site. Is that true?
